name: Suggestion
description: A report of a suggestion, feature request or similar.
title: "[Suggestion]: "
labels: ["enhancement"]
assignees:
  - Gbergz
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing!
        Note that every suggestion you send might not be approved.
  - type: textarea
    id: whats-your-suggestion
    attributes:
      label: What's your suggestion / feature request?
      description: A detailed or short description of your suggestion.
      value: "Text here."
    validations:
      required: true
  - type: textarea
    id: anythingelse
    attributes:
      label: Anything else to add?
      description: Optional.
